# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DsToDhall < Formula
  desc "CLI to translate deploy-sourcegraph YAML to Dhall"
  homepage "https://github.com/sourcegraph/ds-to-dhall"
  version "0.28.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sourcegraph/ds-to-dhall/releases/download/v0.28.0/ds-to-dhall_0.28.0_Darwin_x86_64.tar.gz"
    sha256 "33f0902484b5a1058e3139c2932c029ad22f95fe62d33568ef9389b67e8d0729"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sourcegraph/ds-to-dhall/releases/download/v0.28.0/ds-to-dhall_0.28.0_Linux_x86_64.tar.gz"
    sha256 "8f5ed82ec2201e1c16cd937679746ed87bc734c3af34161b6ad909b0a4224c1c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sourcegraph/ds-to-dhall/releases/download/v0.28.0/ds-to-dhall_0.28.0_Linux_arm64.tar.gz"
    sha256 "1cfd15b926b989c6522f3d52a8ef08039c2b2e7c1e9d152c400b436fda43fbef"
  end

  depends_on "dhall"
  depends_on "dhall-json"
  depends_on "dhall-yaml"
  depends_on "dhall-bash"
  depends_on "dhall-lsp-server"

  def install
    bin.install "ds-to-dhall"
  end

  test do
    system "#{bin}/ds-to-dhall --help"
  end
end
